import Head from 'next/head'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import Post from '../../components/Post'
import CommentModal from '../../components/CommentModal'
import {ArrowLeftIcon } from "@heroicons/react/outline"
import { useRouter } from 'next/router'
import { onSnapshot } from 'firebase/firestore'



export default function feed_post() {
  const router=useRouter()
  const {id} = router.query
  const [post, setPost]=useState()
  useEffect(()=>onSnapshot(doc(db, "posts", id), (snapshot)=>setPost(snapshot)),[db, id])


  return (
    <div>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-7xl mx-auto">
        
      {/*Sidebar*/}
      <Sidebar/>

      <div className="xl:ml-[300px] border-l border-r border-gray-200 xl:min-w-[650px] sm:ml-[100px] flex-grow max-w-xl">
       <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
      <div classname="hoverEffect">
        <ArrowLeftIcon onClick={()=>router.push("/")} className="h-5" />
      </div>
        <h2 className="text-lg sm:text-xl font-bold cursor-pointer">Post</h2>
        
        
       </div>     

       
      <Post id={id} post={post}/>
    </div>

      {/*Widgets*/}
      <Widgets/>

      {/*Modal*/}
      <CommentModal/>


      </main>


    </div>
  )
}
